version: "3"

services:
    react:
        container_name: react
        build: ../react-app/.
        environment:
            - REACT_APP_API_PATH=http://spring:8080
            - CHOKIDAR_USEPOLLING=true
            - CI=true
        ports:
            - 3000:3000
        depends_on:
            - spring
        stdin_open: true
        restart: on-failure

    spring:
        container_name: spring
        build: ../spring-app/.
        environment: 
            - spring.profiles.active=dev,security
            - keycloak.auth-server-url=http://keycloak:8080/auth
        depends_on: 
            - keycloak
        ports:
            - "8080:8080"

    keycloak:
        image: jboss/keycloak:12.0.4
        container_name: keycloak
        environment:
          - KEYCLOAK_USER=admin
          - KEYCLOAK_PASSWORD=admin
          - DB_VENDOR=mysql
          - DB_ADDR=mysql
          - DB_USER=keycloak
          - DB_PASSWORD=password
          - JDBC_PARAMS=useSSL=false
        ports:
          - "9000:8080"
        depends_on:
          - mysql
        healthcheck:
          test: "curl -f http://localhost:8080/auth || exit 1"
          start_period: 20s

    mysql:
        image: mysql:5.7.34
        container_name: mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=keycloak
            - MYSQL_USER=keycloak
            - MYSQL_PASSWORD=password
            - MYSQL_ROOT_PASSWORD=root_password
        healthcheck:
            test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
            start_period: 10s
